[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Ginger = "f3316fcd-6d8d-40c6-bfa5-e1af2871fc6a"
OteraEngine = "b2d7f28f-acd6-4007-8b26-bc27716e5513"

[sources]
Ginger = {path = ".."}

[compat]
BenchmarkTools = "1"
OteraEngine = "1"
julia = "1.13"
