name: Documentation

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      actions: write # allow julia-actions/cache to delete old caches
      contents: write # deploy to the gh-pages branch
      pull-requests: read # required by push_preview = true
      statuses: write # report documentation build status
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: '1.13'
      - uses: julia-actions/cache@v3
      - name: Instantiate docs environment
        run: julia --color=yes --project=docs -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        run: julia --color=yes --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
